name: CI

on:
  # Trigger the workflow on pull request
  pull_request:
    branches:
      - main
  # Trigger the workflow on push
  push:
    branches:
      - main
  # Trigger the workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux, x64, philips-code-hub, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Use Node.js 20.x
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run build
        run: npm run build